### PR TITLE
Use LXQtCompilerSettings

### PR DESCRIPTION
**Pull request by luis-pereira**
It will be increasingly harder to use them. So, the sooner the better.

clazy was used to help in the process of porting from automatic conversions
from 8-bit strings (char *) to unicode QStrings. That was the main barrier.
There's room for improvement for sure.

The foreach Qt commit will be handled in another commit.

### CODE REVIEW

**Comment by agaida** [comment]
thanks @luis-pereira, i wholeheartly agree - will review and in case merge it later this day

**Review by agaida — APPROVED** [review]
Excellent, when rebased and conflicts are resolved.

**Comment by luis-pereira** [comment]
I can re-doit, but it has to be merged before merge conflicts arise.

**Comment by agaida** [comment]
@luis-pereira - GTM - so, please re-do and merge directly

**Comment by luis-pereira** [comment]
Superseded by https://github.com/lxqt/organizer/pull/16

**Pull request closed without merging**
