### PR TITLE
Do translations properly

### LINKED ISSUE #24: Translation hell
Could you please comment a reason you're using custom xml files instead of qt translation system?
https://github.com/lxqt/organizer/blob/4a8484706ea83f863c8219f12df616d05b40d5b3/src/mainwindow.cpp#L449 This way seems to be insane

### PR DESCRIPTION
**Pull request by shlyakpavel**
Fixes https://github.com/lxqt/organizer/issues/24
I recommend not merging https://github.com/lxqt/organizer/pull/26 until I finish this

### CODE REVIEW

**Comment by shlyakpavel** [comment]
Cleanup almost done. Now I have to study how LXQt manages translations in build scripts

**Comment by shlyakpavel** [comment]
Well, it works. It is now ready to be merged. However, there's a special need to reformat current translations into the new format

**Comment by tsujan** [comment]
@shlyakpavel 
I have a suggestion. Since you are an LXQt member and have shown interest in fixing this program, feel free to merge your work on it if it isn't reviewed by others for 3 weeks -- of course, provided that other members don't have an objection. You could also review and/or merge others' works on it.

@all, any objection?

**Comment by shlyakpavel** [comment]
@tsujan could you please review my changes to cmake scripts? I'm not good in cmake and lxqt build system, so any comments on it are appreciated

**Comment by tsujan** [comment]
I'm not good at cmake either ;) But other members are.

I hope you'll revive this project.

**Pull request closed without merging**
