### PR TITLE
Use cpp11 range based for instead of qt foreach

### PR DESCRIPTION
**Pull request by Waqar144**

### CODE REVIEW

**Comment by shlyakpavel** [comment]
This is done by clang-tidy, isn't it?
Looks good.
However, I would prefer to see separate commits: one with `foreach` replacement and the other one with all these `const` qualifiers.
Also, there seems to be a merge conflict. Could you please rebase?

**Comment by Waqar144** [comment]
@shlyakpavel 

The changes in `src/contactmodel.*` are done by clang-tidy. The rest were done by hand, using search

**Comment by shlyakpavel** [comment]
> The changes in `src/contactmodel.*` are done by clang-tidy. The rest were done by hand, using search

Still, these should be separate commits :)

**Comment by Waqar144** [comment]
> > The changes in `src/contactmodel.*` are done by clang-tidy. The rest were done by hand, using search
> 
> Still, these should be separate commits :)

I will do a rebase, and push again with separate commits

**Pull request closed without merging**
