### PR TITLE
Fix auto qstring casts

### PR DESCRIPTION
**Pull request by Waqar144**
Need this to build smoothly. Build fails otherwise due to `QT_NO_CAST_FROM_ASCII`.

### CODE REVIEW

**Comment by shlyakpavel** [comment]
Could you please explain the logic behind calling QLatin1String vs QStringLiteral on the same language names?
P. S. Any operations on the translation code other than deleting it seem to be a waste of time.

**Comment by Waqar144** [comment]
> Could you please explain the logic behind calling QLatin1String vs QStringLiteral on the same language names?

I have used `QLatin1String()` for all the `operator ==` comparisons because `QString` has an overload for it. `QString` also has an overload for `const char*` but for some reason that still causes an allocation. [`clazy docs`](https://github.com/KDE/clazy/blob/master/docs/checks/README-qstring-allocations.md) clarify this as well. `QLatin1String` is a lighter alternative to QString hence using it where possible is better performance wise.

> P. S. Any operations on the translation code other than deleting it seem to be a waste of time.

Hm.. I don't think I understood you here :thinking:

**Comment by shlyakpavel** [comment]
> > P. S. Any operations on the translation code other than deleting it seem to be a waste of time.
> 
> Hm.. I don't think I understood you here 🤔

https://github.com/lxqt/organizer/issues/24

**Comment by Waqar144** [comment]
Well, I suppose it might be a waste of time but until those strings are in there I need them wrapped in `QStringliteral` for build to work.

**Comment by shlyakpavel** [comment]
Okay. <s>I don't mind merging it </s>
P. S. I do mind as it now breaks #28

**Comment by Waqar144** [comment]
> Okay. I don't mind merging it
> P. S. I do mind as it now breaks #28

Yes, indeed. Once that is merged, this PR will be rather useless(mostly). Please close this as soon as you merge that. I will do another PR if `ascii-casts` still remain.

**Comment by ghost** [comment]
@crispinalan 5172121244f847b6cd26fdda1f032de74ab25c88 broke build. Here's the fix:
```diff
diff --git a/src/icons.qrc b/src/icons.qrc
index 59eae74..bf2522f 100755
--- a/src/icons.qrc
+++ b/src/icons.qrc
@@ -4,7 +4,7 @@
         <file>icons/icon-downarrow.svg</file>
         <file>icons/icon-spacebar.svg</file>
         <file>icons/icon-uparrow.svg</file>
-        <file>icons/icon-calendar.png</file>
+        <file>icons/organizer.svg</file>
         <file>icons/icon-f.svg</file>
         <file>icons/icon-r.svg</file>
         <file>icons/icon-d.svg</file>
diff --git a/src/mainwindow.cpp b/src/mainwindow.cpp
index 91cc857..9337c6a 100755
--- a/src/mainwindow.cpp
+++ b/src/mainwindow.cpp
@@ -197,7 +197,7 @@ MainWindow::MainWindow(QWidget *parent) :
     QSound::play(":/sounds/window-attention.wav");
     }
 
-    setWindowIcon(QIcon(":/icons/icon-calendar.png"));
+    setWindowIcon(QIcon(":/icons/organizer.svg"));
     selectedDate = QDate::currentDate();
 
     selectedDateLabel = new QLabel(this);
```

Additionally, I can't build organizer because of the issue discussed in this pull request:
```
[  2%] Automatic MOC and UIC for target organizer
[  2%] Built target organizer_autogen
[  4%] Building CXX object src/CMakeFiles/organizer.dir/mainwindow.cpp.o
/home/ave/Documents/oss/organizer/src/mainwindow.cpp: In constructor ‘MainWindow::MainWindow(QWidget*)’:
/home/ave/Documents/oss/organizer/src/mainwindow.cpp:197:49: error: ‘QString::QString(const char*)’ is private within this context
  197 |     QSound::play(":/sounds/window-attention.wav");
      |                                                 ^
In file included from /usr/include/qt/QtCore/qobject.h:47,
                 from /usr/include/qt/QtWidgets/qwidget.h:45,
                 from /usr/include/qt/QtWidgets/qmainwindow.h:44,
                 from /usr/include/qt/QtWidgets/QMainWindow:1,
                 from /home/ave/Documents/oss/organizer/src/mainwindow.h:21,
                 from /home/ave/Documents/oss/organizer/src/mainwindow.cpp:19:
/usr/include/qt/QtCore/qstring.h:968:5: note: declared private here
  968 |     QString(const char *ch);
      |     ^~~~~~~
/home/ave/Documents/oss/organizer/src/mainwindow.cpp:200:48: error: ‘QString::QString(const char*)’ is private within this context
  200 |     setWindowIcon(QIcon(":/icons/organizer.svg"));
      |                                                ^
In file included from /usr/include/qt/QtCore/qobject.h:47,
                 from /usr/include/qt/QtWidgets/qwidget.h:45,
                 from /usr/include/qt/QtWidgets/qmainwindow.h:44,
                 from /usr/include/qt/QtWidgets/QMainWindow:1,
                 from /home/ave/Documents/oss/organizer/src/mainwindow.h:21,
                 from /home/ave/Documents/oss/organizer/src/mainwindow.cpp:19:
/usr/include/qt/QtCore/qstring.h:968:5: note: declared private here
  968 |     QString(const char *ch);
      |     ^~~~~~~
/home/ave/Documents/oss/organizer/src/mainwindow.cpp:261:79: error: ‘QString::QString(const char*)’ is private within this context
  261 |             ("QLabel { background-color : rgb(81, 186, 242); color : black; }");
      |                                                                               ^
In file included from /usr/include/qt/QtCore/qobject.h:47,
                 from /usr/include/qt/QtWidgets/qwidget.h:45,
                 from /usr/include/qt/QtWidgets/qmainwindow.h:44,
                 from /usr/include/qt/QtWidgets/QMainWindow:1,
                 from /home/ave/Documents/oss/organizer/src/mainwindow.h:21,
                 from /home/ave/Documents/oss/organizer/src/mainwindow.cpp:19:
/usr/include/qt/QtCore/qstring.h:968:5: note: declared private here
  968 |     QString(const char *ch);
      |     ^~~~~~~
/home/ave/Documents/oss/organizer/src/mainwindow.cpp: In member function ‘void MainWindow::checkForReminders()’:
/home/ave/Documents/oss/organizer/src/mainwindow.cpp:394:35: error: ‘QString::QString(const char*)’ is private within this context
  394 |                     str.append(" ");
      |                                   ^
In file included from /usr/include/qt/QtCore/qobject.h:47,
                 from /usr/include/qt/QtWidgets/qwidget.h:45,
                 from /usr/include/qt/QtWidgets/qmainwindow.h:44,
                 from /usr/include/qt/QtWidgets/QMainWindow:1,
                 from /home/ave/Documents/oss/organizer/src/mainwindow.h:21,
                 from /home/ave/Documents/oss/organizer/src/mainwindow.cpp:19:
/usr/include/qt/QtCore/qstring.h:968:5: note: declared private here
  968 |     QString(const char *ch);
      |     ^~~~~~~
/home/ave/Documents/oss/organizer/src/mainwindow.cpp:396:35: error: ‘QString::QString(const char*)’ is private within this context
  396 |                     str.append(" ");
      |                                   ^
In file included from /usr/include/qt/QtCore/qobject.h:47,
                 from /usr/include/qt/QtWidgets/qwidget.h:45,
                 from /usr/include/qt/QtWidgets/qmainwindow.h:44,
                 from /usr/include/qt/QtWidgets/QMainWindow:1,
                 from /home/ave/Documents/oss/organizer/src/mainwindow.h:21,
                 from /home/ave/Documents/oss/organizer/src/mainwindow.cpp:19:
/usr/include/qt/QtCore/qstring.h:968:5: note: declared private here
  968 |     QString(const char *ch);
      |     ^~~~~~~
/home/ave/Documents/oss/organizer/src/mainwindow.cpp:407:35: error: ‘QString::QString(const char*)’ is private within this context
  407 |                     str.append(" ");
      |                                   ^
In file included from /usr/include/qt/QtCore/qobject.h:47,
                 from /usr/include/qt/QtWidgets/qwidget.h:45,
                 from /usr/include/qt/QtWidgets/qmainwindow.h:44,
                 from /usr/include/qt/QtWidgets/QMainWindow:1,
                 from /home/ave/Documents/oss/organizer/src/mainwindow.h:21,
                 from /home/ave/Documents/oss/organizer/src/mainwindow.cpp:19:
/usr/include/qt/QtCore/qstring.h:968:5: note: declared private here
  968 |     QString(const char *ch);
      |     ^~~~~~~
/home/ave/Documents/oss/organizer/src/mainwindow.cpp:409:57: error: ‘QString::QString(const char*)’ is private within this context
  409 |                     str.append(startsAt.toString("hh:mm"));
      |                                                         ^
In file included from /usr/include/qt/QtCore/qobject.h:47,
                 from /usr/include/qt/QtWidgets/qwidget.h:45,
                 from /usr/include/qt/QtWidgets/qmainwindow.h:44,
                 from /usr/include/qt/QtWidgets/QMainWindow:1,
                 from /home/ave/Documents/oss/organizer/src/mainwindow.h:21,
                 from /home/ave/Documents/oss/organizer/src/mainwindow.cpp:19:
/usr/include/qt/QtCore/qstring.h:968:5: note: declared private here
  968 |     QString(const char *ch);
      |     ^~~~~~~
/home/ave/Documents/oss/organizer/src/mainwindow.cpp:411:69: error: ‘QString::QString(const char*)’ is private within this context
  411 |                         QSound::play(":/sounds/window-attention.wav");
      |                                                                     ^
In file included from /usr/include/qt/QtCore/qobject.h:47,
                 from /usr/include/qt/QtWidgets/qwidget.h:45,
                 from /usr/include/qt/QtWidgets/qmainwindow.h:44,
                 from /usr/include/qt/QtWidgets/QMainWindow:1,
                 from /home/ave/Documents/oss/organizer/src/mainwindow.h:21,
                 from /home/ave/Documents/oss/organizer/src/mainwindow.cpp:19:
/usr/include/qt/QtCore/qstring.h:968:5: note: declared private here
  968 |     QString(const char *ch);
      |     ^~~~~~~
/home/ave/Documents/oss/organizer/src/mainwindow.cpp: In member function ‘void MainWindow::setDarkCalendar(int)’:
/home/ave/Documents/oss/organizer/src/mainwindow.cpp:1833:88: error: ‘QString::QString(const char*)’ is private within this context
 1833 |         ui->tableWidgetCalendar->setStyleSheet( "color: black; background-color: white");
      |                                                                                        ^
In file included from /usr/include/qt/QtCore/qobject.h:47,
                 from /usr/include/qt/QtWidgets/qwidget.h:45,
                 from /usr/include/qt/QtWidgets/qmainwindow.h:44,
                 from /usr/include/qt/QtWidgets/QMainWindow:1,
                 from /home/ave/Documents/oss/organizer/src/mainwindow.h:21,
                 from /home/ave/Documents/oss/organizer/src/mainwindow.cpp:19:
/usr/include/qt/QtCore/qstring.h:968:5: note: declared private here
  968 |     QString(const char *ch);
      |     ^~~~~~~
/home/ave/Documents/oss/organizer/src/mainwindow.cpp:1838:99: error: ‘QString::QString(const char*)’ is private within this context
 1838 |         ui->tableWidgetCalendar->setStyleSheet( "color: white; background-color: rgb(105,105,105)");
      |                                                                                                   ^
In file included from /usr/include/qt/QtCore/qobject.h:47,
                 from /usr/include/qt/QtWidgets/qwidget.h:45,
                 from /usr/include/qt/QtWidgets/qmainwindow.h:44,
                 from /usr/include/qt/QtWidgets/QMainWindow:1,
                 from /home/ave/Documents/oss/organizer/src/mainwindow.h:21,
                 from /home/ave/Documents/oss/organizer/src/mainwindow.cpp:19:
/usr/include/qt/QtCore/qstring.h:968:5: note: declared private here
  968 |     QString(const char *ch);
      |     ^~~~~~~
/home/ave/Documents/oss/organizer/src/mainwindow.cpp: In member function ‘void MainWindow::loadSettings()’:
/home/ave/Documents/oss/organizer/src/mainwindow.cpp:1914:43: error: ‘QString::QString(const char*)’ is private within this context
 1914 |     QSettings settings("LXQt", "Organizer");
      |                                           ^
In file included from /usr/include/qt/QtCore/qobject.h:47,
                 from /usr/include/qt/QtWidgets/qwidget.h:45,
                 from /usr/include/qt/QtWidgets/qmainwindow.h:44,
                 from /usr/include/qt/QtWidgets/QMainWindow:1,
                 from /home/ave/Documents/oss/organizer/src/mainwindow.h:21,
                 from /home/ave/Documents/oss/organizer/src/mainwindow.cpp:19:
/usr/include/qt/QtCore/qstring.h:968:5: note: declared private here
  968 |     QString(const char *ch);
      |     ^~~~~~~
/home/ave/Documents/oss/organizer/src/mainwindow.cpp:1914:43: error: ‘QString::QString(const char*)’ is private within this context
 1914 |     QSettings settings("LXQt", "Organizer");
      |                                           ^
In file included from /usr/include/qt/QtCore/qobject.h:47,
                 from /usr/include/qt/QtWidgets/qwidget.h:45,
                 from /usr/include/qt/QtWidgets/qmainwindow.h:44,
                 from /usr/include/qt/QtWidgets/QMainWindow:1,
                 from /home/ave/Documents/oss/organizer/src/mainwindow.h:21,
                 from /home/ave/Documents/oss/organizer/src/mainwindow.cpp:19:
/usr/include/qt/QtCore/qstring.h:968:5: note: declared private here
  968 |     QString(const char *ch);
      |     ^~~~~~~
/home/ave/Documents/oss/organizer/src/mainwindow.cpp:1915:40: error: ‘QString::QString(const char*)’ is private within this context
 1915 |      settings.beginGroup("CoreSettings");
      |                                        ^
In file included from /usr/include/qt/QtCore/qobject.h:47,
                 from /usr/include/qt/QtWidgets/qwidget.h:45,
                 from /usr/include/qt/QtWidgets/qmainwindow.h:44,
                 from /usr/include/qt/QtWidgets/QMainWindow:1,
                 from /home/ave/Documents/oss/organizer/src/mainwindow.h:21,
                 from /home/ave/Documents/oss/organizer/src/mainwindow.cpp:19:
/usr/include/qt/QtCore/qstring.h:968:5: note: declared private here
  968 |     QString(const char *ch);
      |     ^~~~~~~
/home/ave/Documents/oss/organizer/src/mainwindow.cpp:1916:63: error: ‘QString::QString(const char*)’ is private within this context
 1916 |      currentPreferences.m_playAudio=settings.value("PlayAudio").toInt();
      |                                                               ^
In file included from /usr/include/qt/QtCore/qobject.h:47,
                 from /usr/include/qt/QtWidgets/qwidget.h:45,
                 from /usr/include/qt/QtWidgets/qmainwindow.h:44,
                 from /usr/include/qt/QtWidgets/QMainWindow:1,
                 from /home/ave/Documents/oss/organizer/src/mainwindow.h:21,
                 from /home/ave/Documents/oss/organizer/src/mainwindow.cpp:19:
/usr/include/qt/QtCore/qstring.h:968:5: note: declared private here
  968 |     QString(const char *ch);
      |     ^~~~~~~
/home/ave/Documents/oss/organizer/src/mainwindow.cpp:1917:69: error: ‘QString::QString(const char*)’ is private within this context
 1917 |      currentPreferences.m_darkCalendar=settings.value("DarkCalendar").toInt();
      |                                                                     ^
In file included from /usr/include/qt/QtCore/qobject.h:47,
                 from /usr/include/qt/QtWidgets/qwidget.h:45,
                 from /usr/include/qt/QtWidgets/qmainwindow.h:44,
                 from /usr/include/qt/QtWidgets/QMainWindow:1,
                 from /home/ave/Documents/oss/organizer/src/mainwindow.h:21,
                 from /home/ave/Documents/oss/organizer/src/mainwindow.cpp:19:
/usr/include/qt/QtCore/qstring.h:968:5: note: declared private here
  968 |     QString(const char *ch);
      |     ^~~~~~~
/home/ave/Documents/oss/organizer/src/mainwindow.cpp:1918:83: error: ‘QString::QString(const char*)’ is private within this context
 1918 |      currentPreferences.m_applicationFontSize=settings.value("ApplicationFontSize").toInt();
      |                                                                                   ^
In file included from /usr/include/qt/QtCore/qobject.h:47,
                 from /usr/include/qt/QtWidgets/qwidget.h:45,
                 from /usr/include/qt/QtWidgets/qmainwindow.h:44,
                 from /usr/include/qt/QtWidgets/QMainWindow:1,
                 from /home/ave/Documents/oss/organizer/src/mainwindow.h:21,
                 from /home/ave/Documents/oss/organizer/src/mainwindow.cpp:19:
/usr/include/qt/QtCore/qstring.h:968:5: note: declared private here
  968 |     QString(const char *ch);
      |     ^~~~~~~
/home/ave/Documents/oss/organizer/src/mainwindow.cpp:1919:67: error: ‘QString::QString(const char*)’ is private within this context
 1919 |      currentPreferences.m_lineSpacing=settings.value("LineSpacing").toInt();
      |                                                                   ^
In file included from /usr/include/qt/QtCore/qobject.h:47,
                 from /usr/include/qt/QtWidgets/qwidget.h:45,
                 from /usr/include/qt/QtWidgets/qmainwindow.h:44,
                 from /usr/include/qt/QtWidgets/QMainWindow:1,
                 from /home/ave/Documents/oss/organizer/src/mainwindow.h:21,
                 from /home/ave/Documents/oss/organizer/src/mainwindow.cpp:19:
/usr/include/qt/QtCore/qstring.h:968:5: note: declared private here
  968 |     QString(const char *ch);
      |     ^~~~~~~
/home/ave/Documents/oss/organizer/src/mainwindow.cpp: In member function ‘void MainWindow::saveSettings()’:
/home/ave/Documents/oss/organizer/src/mainwindow.cpp:1926:43: error: ‘QString::QString(const char*)’ is private within this context
 1926 |     QSettings settings("LXQt", "Organizer");
      |                                           ^
In file included from /usr/include/qt/QtCore/qobject.h:47,
                 from /usr/include/qt/QtWidgets/qwidget.h:45,
                 from /usr/include/qt/QtWidgets/qmainwindow.h:44,
                 from /usr/include/qt/QtWidgets/QMainWindow:1,
                 from /home/ave/Documents/oss/organizer/src/mainwindow.h:21,
                 from /home/ave/Documents/oss/organizer/src/mainwindow.cpp:19:
/usr/include/qt/QtCore/qstring.h:968:5: note: declared private here
  968 |     QString(const char *ch);
      |     ^~~~~~~
/home/ave/Documents/oss/organizer/src/mainwindow.cpp:1926:43: error: ‘QString::QString(const char*)’ is private within this context
 1926 |     QSettings settings("LXQt", "Organizer");
      |                                           ^
In file included from /usr/include/qt/QtCore/qobject.h:47,
                 from /usr/include/qt/QtWidgets/qwidget.h:45,
                 from /usr/include/qt/QtWidgets/qmainwindow.h:44,
                 from /usr/include/qt/QtWidgets/QMainWindow:1,
                 from /home/ave/Documents/oss/organizer/src/mainwindow.h:21,
                 from /home/ave/Documents/oss/organizer/src/mainwindow.cpp:19:
/usr/include/qt/QtCore/qstring.h:968:5: note: declared private here
  968 |     QString(const char *ch);
      |     ^~~~~~~
/home/ave/Documents/oss/organizer/src/mainwindow.cpp:1927:39: error: ‘QString::QString(const char*)’ is private within this context
 1927 |     settings.beginGroup("CoreSettings");
      |                                       ^
In file included from /usr/include/qt/QtCore/qobject.h:47,
                 from /usr/include/qt/QtWidgets/qwidget.h:45,
                 from /usr/include/qt/QtWidgets/qmainwindow.h:44,
                 from /usr/include/qt/QtWidgets/QMainWindow:1,
                 from /home/ave/Documents/oss/organizer/src/mainwindow.h:21,
                 from /home/ave/Documents/oss/organizer/src/mainwindow.cpp:19:
/usr/include/qt/QtCore/qstring.h:968:5: note: declared private here
  968 |     QString(const char *ch);
      |     ^~~~~~~
/home/ave/Documents/oss/organizer/src/mainwindow.cpp:1928:65: error: ‘QString::QString(const char*)’ is private within this context
 1928 |     settings.setValue("PlayAudio",currentPreferences.m_playAudio);
      |                                                                 ^
In file included from /usr/include/qt/QtCore/qobject.h:47,
                 from /usr/include/qt/QtWidgets/qwidget.h:45,
                 from /usr/include/qt/QtWidgets/qmainwindow.h:44,
                 from /usr/include/qt/QtWidgets/QMainWindow:1,
                 from /home/ave/Documents/oss/organizer/src/mainwindow.h:21,
                 from /home/ave/Documents/oss/organizer/src/mainwindow.cpp:19:
/usr/include/qt/QtCore/qstring.h:968:5: note: declared private here
  968 |     QString(const char *ch);
      |     ^~~~~~~
/home/ave/Documents/oss/organizer/src/mainwindow.cpp:1929:71: error: ‘QString::QString(const char*)’ is private within this context
 1929 |     settings.setValue("DarkCalendar",currentPreferences.m_darkCalendar);
      |                                                                       ^
In file included from /usr/include/qt/QtCore/qobject.h:47,
                 from /usr/include/qt/QtWidgets/qwidget.h:45,
                 from /usr/include/qt/QtWidgets/qmainwindow.h:44,
                 from /usr/include/qt/QtWidgets/QMainWindow:1,
                 from /home/ave/Documents/oss/organizer/src/mainwindow.h:21,
                 from /home/ave/Documents/oss/organizer/src/mainwindow.cpp:19:
/usr/include/qt/QtCore/qstring.h:968:5: note: declared private here
  968 |     QString(const char *ch);
      |     ^~~~~~~
/home/ave/Documents/oss/organizer/src/mainwindow.cpp:1930:85: error: ‘QString::QString(const char*)’ is private within this context
 1930 |     settings.setValue("ApplicationFontSize",currentPreferences.m_applicationFontSize);
      |                                                                                     ^
In file included from /usr/include/qt/QtCore/qobject.h:47,
                 from /usr/include/qt/QtWidgets/qwidget.h:45,
                 from /usr/include/qt/QtWidgets/qmainwindow.h:44,
                 from /usr/include/qt/QtWidgets/QMainWindow:1,
                 from /home/ave/Documents/oss/organizer/src/mainwindow.h:21,
                 from /home/ave/Documents/oss/organizer/src/mainwindow.cpp:19:
/usr/include/qt/QtCore/qstring.h:968:5: note: declared private here
  968 |     QString(const char *ch);
      |     ^~~~~~~
/home/ave/Documents/oss/organizer/src/mainwindow.cpp:1931:69: error: ‘QString::QString(const char*)’ is private within this context
 1931 |     settings.setValue("LineSpacing",currentPreferences.m_lineSpacing);
      |                                                                     ^
In file included from /usr/include/qt/QtCore/qobject.h:47,
                 from /usr/include/qt/QtWidgets/qwidget.h:45,
                 from /usr/include/qt/QtWidgets/qmainwindow.h:44,
                 from /usr/include/qt/QtWidgets/QMainWindow:1,
                 from /home/ave/Documents/oss/organizer/src/mainwindow.h:21,
                 from /home/ave/Documents/oss/organizer/src/mainwindow.cpp:19:
/usr/include/qt/QtCore/qstring.h:968:5: note: declared private here
  968 |     QString(const char *ch);
      |     ^~~~~~~
make[2]: *** [src/CMakeFiles/organizer.dir/build.make:196: src/CMakeFiles/organizer.dir/mainwindow.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:164: src/CMakeFiles/organizer.dir/all] Error 2
make: *** [Makefile:150: all] Error 2
```

I wasn't able to find a workaround for that.

**Pull request closed without merging**
